CREATE TABLE IF NOT EXISTS users(
	user_id INT AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	is_active TINYINT(1) DEFAULT 1 NOT NULL,
	is_admin TINYINT(1) DEFAULT 0 NOT NULL,
	session_uuid VARCHAR(255) NOT NULL
);