CREATE TABLE IF NOT EXISTS evnets ( 
  event_id INT AUTO_INCREMENT PRIMARY KEY, 
  name_of_event VARCHAR(255) NOT NULL, 
  type ENUM('networking', 'campus', 'cultural', 'hobbies', 'sports', 'educational', 'nightlife', 'arts', 'wellbeing'), 
  date DATE NOT NULL,    
  time TIME NOT NULL, 
  name_of_venue VARCHAR(60) NOT NULL, 
  address VARCHAR(255) NOT NULL, 
  city VARCHAR(40) NOT NULL, 
  postal_code VARCHAR(10) NOT NULL, 
  short_description VARCHAR(100) NOT NULL, 
  description VARCHAR(255) NOT NULL, 
  virtual_link VARCHAR(255) NOT NULL, 
  image_url VARCHAR(255) NOT NULL, 
  contact_name VARCHAR(40) NOT NULL, 
  contact_email VARCHAR(255) NOT NULL, 
  contact_phone VARCHAR(10) NOT NULL, 
  name_organization VARCHAR(40) NOT NULL, 
  price INT NOT NULL, 
  event_link VARCHAR(255) NOT NULL, 
  is_approved TINYINT(1) DEFAULT 0 NOT NULL, 
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,    
  inst_id INT NOT NULL,    
  CONSTRAINT fk_event_inst_id FOREIGN KEY (inst_id) REFERENCES institutions(inst_id) ) 
);